-- =====================================================================
-- Real-Time Flights Data Warehouse bootstrap
-- - Staging table (flat, Spark-friendly)
-- - Dimensional model (airline, airport, route)
-- - Fact table (flight status timeline)
-- - Helpful indexes
-- =====================================================================

-- ----------------------------
-- STAGING (truncate/overwrite per batch)
-- ----------------------------
DROP TABLE IF EXISTS fact_flight_status_staging;

CREATE TABLE fact_flight_status_staging (
    -- keys & meta
    flight_key           TEXT                NOT NULL,
    flight_date          DATE,
    -- status
    status               TEXT,  -- producer uses "status"; keep same name here
    ingest_time          TIMESTAMPTZ         NOT NULL DEFAULT NOW(),

    -- flight identifiers
    flight_number        TEXT,
    flight_iata          TEXT,
    flight_icao          TEXT,

    -- airline
    airline_iata         TEXT,
    airline_icao         TEXT,
    airline_name         TEXT,

    -- departure
    dep_airport          TEXT,   -- airport name (if provided)
    dep_airport_iata             TEXT,
    dep_airport_icao             TEXT,
    dep_terminal         TEXT,
    dep_gate             TEXT,
    dep_scheduled        TIMESTAMPTZ,
    dep_estimated        TIMESTAMPTZ,
    dep_actual           TIMESTAMPTZ,
    dep_delay_min        FLOAT              CHECK (dep_delay_min IS NULL OR dep_delay_min >= 0),

    -- arrival
    arr_airport          TEXT,   -- airport name (if provided)
    arr_airport_iata     TEXT,
    arr_airport_icao     TEXT,
    arr_terminal         TEXT,
    arr_gate             TEXT,
    arr_scheduled        TIMESTAMPTZ,
    arr_estimated        TIMESTAMPTZ,
    arr_actual           TIMESTAMPTZ,
    arr_delay_min        FLOAT              CHECK (arr_delay_min IS NULL OR arr_delay_min >= 0)
);

-- Staging indexes
CREATE INDEX IF NOT EXISTS idx_stg_flight_key   ON fact_flight_status_staging (flight_key);
CREATE INDEX IF NOT EXISTS idx_stg_dep_sched    ON fact_flight_status_staging (dep_scheduled);
CREATE INDEX IF NOT EXISTS idx_stg_arr_sched    ON fact_flight_status_staging (arr_scheduled);
CREATE INDEX IF NOT EXISTS idx_stg_airline_iata ON fact_flight_status_staging (airline_iata);


-- ----------------------------
-- DIMENSIONS
-- ----------------------------

-- Airline
DROP TABLE IF EXISTS dim_airline CASCADE;
CREATE TABLE dim_airline (
    airline_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iata            TEXT UNIQUE,         -- 2-char, may be NULL in feed
    icao            TEXT,                -- 3-char, may be NULL
    airline_name    TEXT
);

-- Airport
DROP TABLE IF EXISTS dim_airport CASCADE;
CREATE TABLE dim_airport (
    airport_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iata            TEXT UNIQUE,         -- 3-char IATA (prefer), may be NULL
    icao            TEXT UNIQUE,         -- 4-char ICAO, may be NULL
    airport_name    TEXT
);

-- Route (dep/arr airports)
DROP TABLE IF EXISTS dim_route CASCADE;
CREATE TABLE dim_route (
    route_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dep_airport_id  INTEGER NOT NULL REFERENCES dim_airport(airport_id),
    arr_airport_id  INTEGER NOT NULL REFERENCES dim_airport(airport_id),
    CONSTRAINT uq_route UNIQUE (dep_airport_id, arr_airport_id)
);


-- ----------------------------
-- FACT: flight status timeline
-- ----------------------------
DROP TABLE IF EXISTS fact_flight_status;
CREATE TABLE fact_flight_status (
    flight_key       TEXT PRIMARY KEY,           -- matches producer's stable key
    flight_date      DATE,
    status           TEXT,
    ingest_time      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    airline_id       INTEGER REFERENCES dim_airline(airline_id),
    route_id         INTEGER REFERENCES dim_route(route_id),

    -- departure timeline
    dep_scheduled    TIMESTAMPTZ,
    dep_estimated    TIMESTAMPTZ,
    dep_actual       TIMESTAMPTZ,
    dep_delay_min    FLOAT CHECK (dep_delay_min IS NULL OR dep_delay_min >= 0),

    -- arrival timeline
    arr_scheduled    TIMESTAMPTZ,
    arr_estimated    TIMESTAMPTZ,
    arr_actual       TIMESTAMPTZ,
    arr_delay_min    FLOAT CHECK (arr_delay_min IS NULL OR arr_delay_min >= 0)
);

-- Fact indexes (common filters/joins)
CREATE INDEX IF NOT EXISTS idx_fact_dep_sched     ON fact_flight_status (dep_scheduled);
CREATE INDEX IF NOT EXISTS idx_fact_arr_sched     ON fact_flight_status (arr_scheduled);
CREATE INDEX IF NOT EXISTS idx_fact_airline_id    ON fact_flight_status (airline_id);
CREATE INDEX IF NOT EXISTS idx_fact_route_id      ON fact_flight_status (route_id);
CREATE INDEX IF NOT EXISTS idx_fact_flight_date   ON fact_flight_status (flight_date);
